---
- hosts: install-hosts
  become: yes
  roles:
    - hypervisor

- hosts: openshift
  become: yes
  roles:
    - openshift-common

- hosts: node
  become: yes
  roles:
    - openshift-node

- hosts: master
  become: yes
  roles:
    - openshift-master
