kind: Template
apiVersion: v1
labels:
  template: tensorflow-sc17
metadata:
 name: "tensorflow-server-s2i"
 annotations:
  description: Tensorflow Demo for SC 17
  tags: tensorflow,oia,sc17,demo
  icon-class: icon-beakericon-beaker
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
   name: "${APPLICATION_NAME}"
   labels:
    appid: "tf-app-server-${APPLICATION_NAME}"
    appName: "${APPLICATION_NAME}"
- kind: ImageStream
  apiVersion: v1
  metadata:
   name: "${APPLICATION_NAME}-s2i"
   labels:
    appid: "tf-app-server-${APPLICATION_NAME}"
    appName: "${APPLICATION_NAME}"
  spec:
   tags:
   - name: latest
     from:
      kind: DockerImage
      name: "radanalyticsio/tensorflow-serving-s2i:latest"
- kind: BuildConfig
  apiVersion: v1
  metadata:
   name: "${APPLICATION_NAME}"
   labels:
    appid: "tf-app-server-${APPLICATION_NAME}"
    appName: "${APPLICATION_NAME}"
  spec:
   triggers:
   - type: ConfigChange
   - type: ImageChange
   source:
    type: Git
    git:
     uri: "${SOURCE_REPOSITORY}"
    contextDir: "${SOURCE_DIRECTORY}"
   strategy:
    type: Source
    sourceStrategy:
     from:
      kind: ImageStreamTag
      name: "${APPLICATION_NAME}-s2i:latest"
   output:
    to:
     kind: ImageStreamTag
     name: "${APPLICATION_NAME}:latest"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
   name: "${APPLICATION_NAME}"
   labels:
    appid: "tf-app-server-${APPLICATION_NAME}"
    appName: "${APPLICATION_NAME}"
  spec:
   strategy:
    type: Rolling
   triggers:
   - type: ConfigChange
   - type: ImageChange
     imageChangeParams:
      automatic: true
      containerNames:
      - "${APPLICATION_NAME}"
      from:
       kind: ImageStreamTag
       name: "${APPLICATION_NAME}:latest"
   replicas: 1
   selector:
    deploymentconfig: "${APPLICATION_NAME}"
   template:
    metadata:
     labels:
      appid: "tf-app-server-${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
      appName: "${APPLICATION_NAME}"
    spec:
     containers:
     - name: "${APPLICATION_NAME}"
       image: "${APPLICATION_NAME}:latest"
       ports:
       - containerPort: 6006
         protocol: TCP
- kind: Service
  apiVersion: v1
  metadata:
   name: "${APPLICATION_NAME}"
   labels:
    appid: "tf-app-server-${APPLICATION_NAME}"
    appName: "${APPLICATION_NAME}"
  spec:
   ports:
   - name: "6006-tcp"
     protocol: TCP
     port: 6006
     targetPort: 6006
   selector:
    deploymentconfig: "${APPLICATION_NAME}"
parameters:
- name: APPLICATION_NAME
  description: "The name of the application."
  value: "tf-app-server"
  from: "[a-zA-Z0-9]{10}"
  required: true
- name: SOURCE_REPOSITORY
  description: "Git repository for source."
  value: ""
  required: true
- name: SOURCE_DIRECTORY
  description: "Sub-directory of repository for source files."
  value: ""
  required: false
